using Inspection_of_Measuring_Instruments.Domain.Entities.InspectionEntities;

namespace Inspection_of_Measuring_Instruments.Application.Repositories.InspectionRepositories;

public interface IScaleInspectionWriteRepository : IWriteRepository<ScaleInspection>
{

}